# Generated by Django 4.0.2 on 2022-03-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_department_alter_register_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_course',
            name='codepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.department'),
        ),
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo15.png', upload_to='Profile Pic'),
        ),
    ]
